README.md, config/database.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-473)
=> EL-473 update readme with reasons for the fork

app/models/applicant_capital_summary.rb, app/models/applicant_disposable_income_summary.rb, app/models/applicant_employment.rb, app/models/applicant_gross_income_summary.rb, app/models/assessment.rb, app/models/partner.rb, app/models/partner_capital_summary.rb, app/models/partner_disposable_income_summary.rb, app/models/partner_employment.rb, app/models/partner_gross_income_summary.rb, app/services/decorators/v5/proceeding_types_result_decorator.rb, db/migrate/20221114092809_create_partners.rb, db/schema.rb, spec/services/creators/capitals_creator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-464)
Added new database elements and ActiveRecord classes to accommodate partner financial info
=> EL-464: partner data model

app/controllers/partner_financials_controller.rb, app/models/partner.rb, app/services/creators/capitals_creator.rb, app/services/creators/employments_creator.rb, app/services/creators/irregular_income_creator.rb, app/services/creators/partner_financials_creator.rb, app/services/creators/partner_properties_creator.rb, app/services/creators/regular_transactions_creator.rb, app/services/creators/state_benefits_creator.rb, app/services/creators/vehicle_creator.rb, config/routes.rb, public/schemas/additional_properties.json.erb, public/schemas/partner.json.erb, spec/factories/partner_factory.rb, spec/fixtures/partner_financials.json, spec/requests/swagger_docs/v5/partner_financials_spec.rb, spec/services/creators/partner_financials_creator_spec.rb, swagger/v5/swagger.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/EL-465)
Add a new endpoint to receive partner data.
Reuse existing Creators where possible to handle persistence of params into DB.
=> EL-465: partner endpoint

app/controllers/partner_financials_controller.rb, app/services/creators/capitals_creator.rb, app/services/creators/employments_creator.rb, app/services/creators/irregular_income_creator.rb, app/services/creators/partner_financials_creator.rb, app/services/creators/partner_properties_creator.rb, app/services/creators/regular_transactions_creator.rb, app/services/creators/state_benefits_creator.rb, app/services/creators/vehicle_creator.rb, config/routes.rb, public/schemas/additional_properties.json.erb, public/schemas/partner.json.erb, spec/factories/partner_factory.rb, spec/fixtures/partner_financials.json, spec/requests/swagger_docs/v5/partner_financials_spec.rb, spec/services/creators/partner_financials_creator_spec.rb, swagger/v5/swagger.yaml
I merged the previous PR into the wrong place
=> EL-465 partner endpoint: second attempt at merging

app/services/decorators/v5/assessment_decorator.rb, app/services/decorators/v5/capital_decorator.rb, app/services/decorators/v5/capital_result_decorator.rb, app/services/decorators/v5/disposable_income_decorator.rb, app/services/decorators/v5/disposable_income_result_decorator.rb, app/services/decorators/v5/gross_income_decorator.rb, app/services/decorators/v5/gross_income_result_decorator.rb, app/services/decorators/v5/proceeding_types_result_decorator.rb, app/services/decorators/v5/result_summary_decorator.rb, spec/services/decorators/v5/assessment_decorator_spec.rb, spec/services/decorators/v5/capital_result_decorator_spec.rb, spec/services/decorators/v5/disposable_income_result_decorator_spec.rb, spec/services/decorators/v5/gross_income_decorator_spec.rb, spec/services/decorators/v5/gross_income_result_decorator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-467)
=> EL-467: output payload

app/lib/applicant_or_partner_wrapper.rb, app/lib/person_wrapper.rb, app/services/assessors/disposable_income_assessor.rb, app/services/calculators/housing_costs_calculator.rb, app/services/calculators/income_contribution_calculator.rb, app/services/collators/childcare_collator.rb, app/services/collators/disposable_income_collator.rb, app/services/collators/housing_costs_collator.rb, app/services/collators/outgoings_collator.rb, app/services/collators/regular_income_collator.rb, app/services/collators/regular_outgoings_collator.rb, app/services/concerns/monthly_equivalent_calculatable.rb, app/services/workflows/non_passported_workflow.rb, spec/factories/cash_transaction_category_factory.rb, spec/factories/employment_factory.rb, spec/factories/irregular_income_payment_factory.rb, spec/factories/regular_transaction_factory.rb, spec/services/assessors/disposable_income_assessor_spec.rb, spec/services/calculators/housing_costs_calculator_spec.rb, spec/services/collators/childcare_collator_spec.rb, spec/services/collators/housing_costs_collator_spec.rb, spec/services/collators/outgoings_collator_spec.rb, spec/services/collators/regular_outgoings_collator_spec.rb, spec/services/workflows/non_passported_workflow_spec.rb
https://dsdmoj.atlassian.net/browse/EL-485
Introduce rule that specifies that the housing cost cap is removed for both calculations if client has a partner
=> EL-485 - remove housing costs cap if applicant has a partner

app/services/workflows/non_passported_workflow.rb, config/thresholds/2022-04-11.yml, spec/factories/employment_factory.rb, spec/factories/partner_factory.rb, spec/services/workflows/non_passported_workflow_spec.rb
https://dsdmoj.atlassian.net/browse/EL-486
Add partner allowance into disposable income calculation when partner is included in calculation
=> EL-486 add partner allowance threshold to disposable income calculation

app/services/collators/childcare_collator.rb, app/services/collators/regular_outgoings_collator.rb, app/services/concerns/childcare_eligibility.rb, app/services/workflows/non_passported_workflow.rb, lib/integration_helpers/test_case/applicant.rb, spec/factories/dependant_factory.rb, spec/services/collators/regular_outgoings_collator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-490)
Attempting to reuse https://github.com/ministryofjustice/check-financial-eligibility/pull/1199 which fixes this on the main fork, although the diverging codebases means a lot had to be adjusted.
=> EL-490: Assess childcare eligibility when considering childcare costs

app/models/eligibility/capital.rb, app/services/assessors/capital_assessor.rb, app/services/assessors/liquid_capital_assessor.rb, app/services/assessors/non_liquid_capital_assessor.rb, app/services/assessors/vehicle_assessor.rb, app/services/calculators/pensioner_capital_disregard_calculator.rb, app/services/calculators/property_calculator.rb, app/services/calculators/subject_matter_of_dispute_disregard_calculator.rb, app/services/capital_collator_and_assessor.rb, app/services/collators/capital_collator.rb, app/services/workflows/non_passported_workflow.rb, app/services/workflows/passported_workflow.rb, spec/factories/partner_factory.rb, spec/services/assessors/liquid_capital_assessor_spec.rb, spec/services/assessors/non_liquid_capital_assessor_spec.rb, spec/services/assessors/vehicle_assessor_spec.rb, spec/services/calculators/pensioner_capital_disregard_calculator_spec.rb, spec/services/calculators/property_calculator_spec.rb, spec/services/calculators/subject_matter_of_dispute_disregard_calculator_spec.rb, spec/services/collators/capital_collator_spec.rb, spec/services/workflows/non_passported_workflow_spec.rb, spec/services/workflows/passported_workflow_spec.rb
https://dsdmoj.atlassian.net/browse/EL-487
Add partner capital calculations. The 2 changes are to use the sum of partner capital assets to assess thresholds, and to allow the partner being over 60 to enable the pensioner capital disregard figure
=> EL-487 partner capital calculations

app/services/capital_collator_and_assessor.rb, app/services/decorators/v5/capital_result_decorator.rb, app/services/decorators/v5/disposable_income_result_decorator.rb, app/services/decorators/v5/gross_income_result_decorator.rb, app/services/decorators/v5/vehicle_decorator.rb, app/services/workflows/non_passported_workflow.rb, db/migrate/20221123103859_add_combined_total_gross_income_to_gross_income_summary.rb, db/schema.rb, spec/services/decorators/v5/capital_result_decorator_spec.rb, spec/services/decorators/v5/disposable_income_result_decorator_spec.rb, spec/services/decorators/v5/gross_income_result_decorator_spec.rb, spec/services/decorators/v5/vehicle_decorator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-471)
Store combined total values in the DB for gross and disposable income and capital, and expose it in the response payload
=> EL-471: result payload additions

app/services/collators/disposable_income_collator.rb, app/services/workflows/non_passported_workflow.rb, spec/services/collators/disposable_income_collator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-512)
Add `partner allowance` into the outgoings total, rather than subtracting it from gross income separately.
=> EL-512: Add partner allowance into outgoings subtotal

.circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/browse/EL-524)
Run integration tests as part of the 'merge_pr' workflow, not just the 'add_branch' one.
=> EL-524 integration tests on merge

features/disputed_assets/disputed_capital_items.feature, features/disputed_assets/disputed_property.feature, features/disputed_assets/disputed_vehicle.feature, features/step_definitions/api_request.rb, features/support/request_support_methods.rb, features/support/response_support_methods.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-518)
Belated cucumber tests describing overview of SMOD functionality
=> EL-518:Cucumber coverage for SMOD functionality

features/partner/partner_assessment.feature, features/step_definitions/api_request.rb, features/support/response_support_methods.rb, spec/rails_helper.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-520)
Add cucumber tests to test the partner CFE assessment
Added tests for capital, employment and capital and employment with varying degrees of pensioner applicant/partners
Happy to extend or add tests if this doesnt meet the ticket criteria (i think it does but 🤷 ), most of my time was spent understanding how it all worked so i am happy I can extend or change the tests as requested
- The PR description should say what you changed and …
=> El 520 partner cucumber tests

deploy/helm/templates/deployment_web.yaml
See: https://github.com/puma/puma/blob/master/docs/kubernetes.md#running-puma-in-kubernetes
[Link to story](https://dsdmoj.atlassian.net/browse/AP-569)
=> EL-569 Workaround for Puma/k8s dropped request problem

.circleci/config.yml
https://dsdmoj.atlassian.net/browse/EL-558
Add production approval step so that production releases of CFE can be tightly controlled
=> EL-558 add production approval step for CFE Partner

.github/actions/delete-uat-release/action.yml, .github/workflows/brakeman-analysis.yml, .github/workflows/delete-uat-release.yml
[Link to story](https://dsdmoj.atlassian.net/browse/EL-546)
When a PR is closed, remove the associated K8s release - [see example of it running successfully](https://github.com/ministryofjustice/check-financial-eligibility-partner/actions/runs/3713947689).
=> EL-546 delete K8s release on closed PR

.github/workflows/brakeman-analysis.yml, .github/workflows/codeql-analysis.yml, .github/workflows/docker-image-scan.yaml, .github/workflows/manual-integration-tests.yml
As mentioned here by Colin https://mojdt.slack.com/archives/C040DEGBZQQ/p1672739292430719
this update was required on CFE-Partner actions
=> Update github actions versions

app/models/assessment.rb, app/services/creators/assessment_creator.rb, config/initializers/inflections.rb, db/migrate/20230120122437_add_level_of_representation_to_assessments.rb, db/schema.rb, public/schemas/assessment.json.erb, spec/requests/swagger_docs/v5/assessments_spec.rb, spec/services/creators/assessment_creator_spec.rb, swagger/v5/swagger.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/EL-631)
Clients can flag if assessment is for controlled work
=> EL-631: Support controlled work flag

README.md, spec/requests/swagger_docs/v5/vehicles_spec.rb, swagger/v5/swagger.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/EL-624)
Update wordings to encompass controlled work changes
=> EL-624: Wording changes

app/services/assessors/capital_assessor.rb, app/services/capital_collator_and_assessor.rb, app/services/collators/capital_collator.rb, app/services/decorators/v5/capital_result_decorator.rb, app/services/decorators/v5/result_summary_decorator.rb, db/migrate/20230125161914_remove_combined_capital_contribution_from_capital_summary.rb, db/schema.rb, features/partner/partner_assessment.feature, features/step_definitions/api_request.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-637)
Calculate capital contribution based on combined client and partner capital
=> EL-637: Fix bug working out capital contribution

app/services/creators/capital_eligibility_creator.rb, app/services/creators/disposable_income_eligibility_creator.rb, app/services/creators/gross_income_eligibility_creator.rb, app/services/utilities/proceeding_type_threshold_populator.rb, config/thresholds/2018-04-08.yml, config/thresholds/2019-04-08.yml, config/thresholds/2020-04-06.yml, config/thresholds/2021-01-28.yml, config/thresholds/2021-04-12.yml, config/thresholds/2022-04-11.yml, config/thresholds/test-jan.yml, features/controlled_work/controlled_thresholds.feature, features/controlled_work/property_assessment.feature, features/step_definitions/api_request.rb, spec/data/simple_thresholds.yml, spec/data/thresholds/2018-04-08.yml, spec/data/thresholds/2019-04-08.yml, spec/data/thresholds/2020-04-08.yml, spec/data/thresholds/2021-01-28.yml, spec/data/thresholds/test_only_2020-12-15.yml, spec/models/proceeding_type_threshold_spec.rb, spec/models/threshold_spec.rb, spec/services/creators/capital_eligibility_creator_spec.rb, spec/services/creators/disposable_income_eligibiltiy_creator_spec.rb, spec/services/utilities/proceeding_type_threshold_populator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-623)
New logic to apply different lower thresholds for controlled work (equal to upper thresholds, so "contribution required" results are not possible), and also to ignore Domestic Abuse waiver for upper threshold for controlled work.
- …
=> EL-623: controlled work thresholds

app/lib/calculation_output.rb, features/partner/partner_assessment.feature, features/step_definitions/api_request.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-720)
Ensure we always have a partner_capital_subtotals object
=> EL-720: Error message displayed when user submits eligibility check

deploy/helm/values/production.yaml, deploy/helm/values/staging.yaml, deploy/helm/values/uat.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-721)
Sentry is working again. I have rate limited our live keys to process 10 events an hour, and this can be adjusted easily via the Sentry UI
- Tests and rubocop should be passing
- Branch is generally up to date with main Github - definitely no conflicts
- No unnecessary whitespace changes. These make diffs harder to read and conflicts more likely.
- PR description says *what* changed and *why*, with a link to the JIRA story.
- Diff has been checked for unexpected changes being included.
- Commit messages say why the change was made.
=> EL-721: Enable Sentry in all environments

app/models/assessment.rb, app/services/assessors/property_assessor.rb, app/services/calculators/property_calculator.rb, app/services/capital_collator_and_assessor.rb, app/services/collators/capital_collator.rb, app/services/creators/assessment_creator.rb, app/services/creators/capital_eligibility_creator.rb, app/services/creators/disposable_income_eligibility_creator.rb, app/services/utilities/proceeding_type_threshold_populator.rb, config/initializers/inflections.rb, db/migrate/20230225142836_rename_level_of_representation.rb, db/schema.rb, features/step_definitions/api_request.rb, public/schemas/assessment.json.erb, spec/requests/swagger_docs/v5/assessments_spec.rb, spec/requests/swagger_docs/v5/full_assessment_spec.rb, spec/services/calculators/property_calculator_spec.rb, spec/services/collators/capital_collator_spec.rb, spec/services/creators/assessment_creator_spec.rb, spec/services/creators/capital_eligibility_creator_spec.rb, spec/services/creators/disposable_income_eligibiltiy_creator_spec.rb, spec/services/utilities/proceeding_type_threshold_populator_spec.rb, spec/services/workflows/non_passported_workflow_spec.rb, swagger/v5/swagger.yaml
https://dsdmoj.atlassian.net/browse/EL-723
Accept 'level_of_help' as a synonym of 'level of representation' so that it can be renamed safely in the one client (CCQ) that sets it w/o causing issues in UAT or production
=> EL-723 Part One - synonyms 'level of help' and 'level of representation'

app/services/calculators/employment_income_calculator.rb, app/services/creators/employments_creator.rb, db/migrate/20230215110407_add_receives_asylum_support_to_applicants.rb, db/migrate/20230223153716_add_receiving_only_statutory_sick_or_maternity_pay_to_employments.rb, db/schema.rb, features/employment/statutory_pay.feature, features/step_definitions/api_request.rb, features/support/response_support_methods.rb, public/schemas/employment.json.erb, spec/requests/swagger_docs/v5/employments_spec.rb, spec/requests/swagger_docs/v5/full_assessment_spec.rb, spec/services/calculators/employment_income_calculator_spec.rb, spec/services/creators/employments_creator_spec.rb, swagger/v5/swagger.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/EL-722)
Add statutory pay flag
=> EL-722: Rules governing statutory sick/maternity pay

app/lib/person_capital_subtotals.rb, app/services/collators/capital_collator.rb, app/services/decorators/v5/capital_result_decorator.rb, spec/requests/swagger_docs/v5/full_assessment_spec.rb, spec/requests/v2/assessments_controller_spec.rb, spec/services/decorators/v5/capital_result_decorator_spec.rb, swagger/v5/swagger.yaml
https://dsdmoj.atlassian.net/browse/EL-767
=> EL-767 Expose total capital after SMOD disregard applied

public/schemas/applicant_v5.json.erb, public/schemas/assessment.json.erb, public/schemas/cash_transaction.json.erb, public/schemas/common.json, public/schemas/dependants.json.erb, public/schemas/employment.json.erb, public/schemas/other_incomes.json.erb, public/schemas/outgoings.json.erb, public/schemas/state_benefits.json.erb, public/schemas/vehicles.json.erb, spec/requests/applicants_controller_spec.rb, spec/requests/v2/assessments_controller_spec.rb, spec/validators/json_validator_spec.rb
https://dsdmoj.atlassian.net/browse/EL-737
=> EL-737 convert JSON date formatting for format: :string, type: :date

app/services/calculators/housing_costs_calculator.rb, app/services/creators/partner_properties_creator.rb, app/services/creators/state_benefits_creator.rb, spec/services/collators/outgoings_collator_spec.rb, spec/spec_helper.rb
=> EL-710 remove obvious redundant nil checks

app/services/remark_generators/frequency_checker.rb, app/services/remark_generators/orchestrator.rb, spec/spec_helper.rb
Remove redundant nil checks from Remarks Orchestrator class. Most were active record has_many associations. Also remove redundant code from FrequencyChecker class
=> EL-710 remove redundant nil checks in Remarks Orchestrator

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, spec/requests/application_controller_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-28
Replace custom rescue_from in ApplicationController so that everything isn't a 422 error
=> LEP-28 replace custom rescue_from with gem version 

spec/requests/cash_transactions_controller_spec.rb
Whilst looking at test coverage, this spec was found that didn't check for success, and was actually crashing
=> EL-710 Fix up spec that was crashing but not checked for success

app/controllers/application_controller.rb, app/controllers/employments_controller.rb, app/models/employment_payment.rb, app/services/creators/employments_creator.rb, app/services/creators/full_assessment_creator.rb, app/services/creators/partner_financials_creator.rb, lib/integration_helpers/test_case/employment_collection.rb, public/schemas/employment.json.erb, spec/fixtures/employments.json, spec/fixtures/partner_financials.json, spec/integration_helpers/test_case/employment_collection_spec.rb, spec/models/employment_payment_spec.rb, spec/requests/employments_controller_spec.rb, spec/requests/swagger_docs/v5/employments_spec.rb, spec/requests/swagger_docs/v5/full_assessment_spec.rb, spec/requests/swagger_docs/v5/partner_financials_spec.rb, spec/services/creators/employments_creator_spec.rb, spec/services/creators/partner_financials_creator_spec.rb, spec/swagger_helper.rb, swagger/v5/swagger.yaml
https://dsdmoj.atlassian.net/browse/EL-739
=> EL-739 remove net employment input

app/services/capital_collator_and_assessor.rb, app/services/decorators/v5/capital_result_decorator.rb, features/partner/partner_assessment.feature, features/pensioner/pensioner_disregard.feature, features/step_definitions/api_request.rb, features/support/response_support_methods.rb, spec/requests/v2/assessments_controller_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-49
=> LEP-49 Pensioner disregard split across client and partner assets

app/controllers/application_controller.rb, spec/services/calculators/tax_ni_refund_calculator_spec.rb, spec/spec_helper.rb
Add missing coverage test for tax/NI refund calculator, and tidy up application controller single/many messages code
=> EL-710 - tax/NI refund calculator

app/controllers/irregular_incomes_controller.rb, app/services/creators/full_assessment_creator.rb, app/services/creators/irregular_income_creator.rb, app/services/creators/other_incomes_creator.rb, app/services/creators/outgoings_creator.rb, app/services/creators/partner_financials_creator.rb, app/services/creators/proceeding_types_creator.rb, features/CCC_CFE_Integration_Test_V3/NPE10-4-V5.feature, lib/integration_helpers/test_case/worksheet.rb, spec/integration/test_runner_spec.rb, spec/requests/outgoings_controller_spec.rb, spec/requests/swagger_docs/v5/outgoings_spec.rb, spec/services/creators/irregular_income_creator_spec.rb, spec/services/creators/outgoings_creator_spec.rb, spec/spec_helper.rb
https://dsdmoj.atlassian.net/browse/LEP-17
Run spreadsheet examples through the single-shot API to provide confidence that it has been implemented correctly
=> LEP-17 Run spreadsheet examples through single-shot API

app/services/creators/assessment_creator.rb, public/schemas/assessment.json.erb, spec/requests/swagger_docs/v5/assessments_spec.rb, spec/services/creators/assessment_creator_spec.rb, swagger/v5/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-19
Follow up to renaming level_of_representation - remove synonym now CCQ no longer relies on it
=> LEP-19: Remove level_of_representation synonym for level_of_help

app/services/collators/capital_collator.rb, features/disputed_assets/disputed_pensioner_assets.feature
https://dsdmoj.atlassian.net/browse/LEP-51
Pensioner disregard applied field displayed incorrectly, no effect on eligibility calculation
=> Lep 51 pensioner disregard with smod

app/services/calculators/property_calculator.rb, app/services/collators/capital_collator.rb, features/disputed_assets/disputed_property.feature, features/disputed_assets/disputed_vehicle.feature, features/disputed_assets/multiple_disputed_assets.feature, features/partner/partner_assessment.feature, spec/services/calculators/property_calculator_spec.rb, spec/services/decorators/v5/property_decorator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-53
Fix issue with reporting of main_home_equity_disregard value
=> LEP 53 FIX main home equity disregard

app/services/calculators/property_calculator.rb
https://dsdmoj.atlassian.net/browse/LEP-53
Address review comments missed during merge
=> LEP-53: tidy up functions and variable names

app/controllers/capitals_controller.rb, app/services/creators/capitals_creator.rb, app/services/creators/full_assessment_creator.rb, app/services/creators/partner_financials_creator.rb, spec/services/creators/capitals_creator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-27
=> LEP-27 - spike moving schema validation to controller

app/services/decorators/v5/capital_result_decorator.rb, spec/requests/swagger_docs/v5/full_assessment_spec.rb, spec/requests/v2/assessments_controller_spec.rb, spec/services/decorators/v5/capital_result_decorator_spec.rb, swagger/v5/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-59
=> LEP-59: remove (unused) combined_capital_contribution field

config/thresholds/2023-04-10.yml, config/thresholds/values.yml, features/partner/partner_assessment.feature, features/step_definitions/api_request.rb, features/support/response_support_methods.rb
https://dsdmoj.atlassian.net/browse/LEP-54
=> LEP-54 change partner and dependant thresholds for 10th April 2023

app/services/workflows/non_passported_workflow.rb, features/partner/partner_assessment.feature, spec/requests/v2/assessments_controller_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-59
In EL-688, a minor defect was discovered and fixed. This fixes the defect independently so we can have more confidence in the large number of changes introduced in EL-688.
=> LEP-59: Allocate partner allowance to client not to partner

app/controllers/capitals_controller.rb, app/services/creators/capitals_creator.rb, app/services/creators/full_assessment_creator.rb, app/services/creators/partner_financials_creator.rb, public/schemas/capitals.json.erb, spec/services/creators/capitals_creator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-27
Move schema validation into controller layer for capitals, so that when we stop calling creators validation will still take place on the endpoints
=> LEP-27 move schema validation up to controller

spec/rails_helper.rb, spec/requests/v2/assessments_controller_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-63
Extract improved test out of code changes
=> LEP-63 Part I - improve controller test

spec/requests/v2/assessments_controller_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-63
Add all transaction types to cash_transactions spec - will probably show up another defect in EL-688 as legal_aid cash transactions ignored
=> LEP-63 improve cash_transactions spec

app/lib/gross_income_subtotals.rb, app/services/decorators/v5/gross_income_result_decorator.rb, app/services/decorators/v5/result_summary_decorator.rb, app/services/workflows/non_passported_workflow.rb, spec/services/decorators/v5/assessment_decorator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-63
add a small amount of behaviour to GrossIncomeSubtotals
=> LEP-63 give subtotals object a small amount of behaviour

features/controlled_work/controlled_thresholds.feature, features/controlled_work/property_assessment.feature, features/disputed_assets/disputed_capital_items.feature, features/disputed_assets/disputed_pensioner_assets.feature, features/disputed_assets/disputed_property.feature, features/disputed_assets/disputed_vehicle.feature, features/disputed_assets/multiple_disputed_assets.feature, features/partner/partner_assessment.feature, features/pensioner/pensioner_disregard.feature, features/property/property.feature, features/step_definitions/api_request.rb
https://dsdmoj.atlassian.net/browse/LEP-61
Refactor cucumber infrastructure into smaller pieces - 'pensioner', 'passported', 'asylum', 'immigration', 'domestic abuse'
=> LEP-61 refactor cucumber test infrastructure

app/services/calculators/housing_costs_calculator.rb, app/services/collators/childcare_collator.rb, app/services/collators/dependants_allowance_collator.rb, app/services/collators/housing_costs_collator.rb, app/services/collators/legal_aid_collator.rb, app/services/collators/maintenance_collator.rb, app/services/collators/outgoings_collator.rb, app/services/decorators/v5/disposable_income_decorator.rb, spec/services/collators/childcare_collator_spec.rb, spec/services/collators/dependants_allowance_collator_spec.rb, spec/services/collators/disposable_income_collator_spec.rb, spec/services/collators/housing_costs_collator_spec.rb, spec/services/collators/legal_aid_collator_spec.rb, spec/services/collators/maintenance_collator_spec.rb, spec/services/collators/outgoings_collator_spec.rb, spec/services/utilities/employment_income_monthly_equivalent_calculator_spec.rb, spec/services/workflows/non_passported_workflow_spec.rb, spec/spec_helper.rb
https://dsdmoj.atlassian.net/browse/LEP-63
Bring in some of LEP-22 / EL-688 to help understand housing costs refactor
=> LEP-63 Part II move updating of disposable_income_summary up the call stack

app/services/decorators/v5/assessment_decorator.rb, spec/requests/swagger_docs/v5/full_assessment_spec.rb, spec/requests/v2/assessments_controller_spec.rb, spec/services/decorators/v5/assessment_decorator_spec.rb, swagger/v5/swagger.yaml
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/LEP/boards/1143?modal=detail&selectedIssue=LEP-48)
1. Exposed level_of_help in the response from the API call
2. Updated rspec files to suit
3. regenerated swagger.yaml 
- You should have …
=> LEP-48 exposed level_of_help in response from API

Gemfile, Gemfile.lock, Guardfile, README.md
[LEP-60](https://dsdmoj.atlassian.net/browse/LEP-60)
Add guard support for the following tasks to save development time
- rubocop
- rspec
- cucumber
- swagger
[LEP-60]: https://dsdmoj.atlassian.net/browse/LEP-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LEP-60 Add guard support

app/constants/cfe_constants.rb, app/controllers/v6/assessments_controller.rb, app/services/creators/full_assessment_creator.rb, config/routes.rb, features/step_definitions/api_request.rb, features/support/response_support_methods.rb, spec/integration/test_runner_spec.rb, spec/requests/swagger_docs/v5/full_assessment_spec.rb, spec/requests/v6/assessments_controller_spec.rb, spec/swagger_helper.rb, swagger/v5/swagger.yaml
(https://dsdmoj.atlassian.net/browse/LEP-85
=> LEP-85: Rename single-shot API endpoint as 'v6'

app/controllers/assessments_controller.rb, app/controllers/irregular_incomes_controller.rb, app/controllers/partner_financials_controller.rb, app/controllers/v6/assessments_controller.rb, app/services/creators/assessment_creator.rb, app/services/creators/full_assessment_creator.rb, app/services/creators/irregular_income_creator.rb, app/services/creators/partner_financials_creator.rb, app/validators/json_swagger_validator.rb, features/controlled_work/controlled_thresholds.feature, features/pensioner/pensioner_disregard.feature, features/step_definitions/api_request.rb, lib/integration_helpers/test_case/outgoings_collection.rb, lib/integration_helpers/test_case/payment.rb, spec/requests/irregular_incomes_controller_spec.rb, spec/requests/partner_financials_controller_spec.rb, spec/requests/swagger_docs/v5/partner_financials_spec.rb, spec/requests/v6/assessments_controller_spec.rb, spec/services/creators/irregular_income_creator_spec.rb, spec/services/creators/partner_financials_creator_spec.rb, swagger/v5/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-77
Move validation to controller-level for partner and single-shot API. 
Fix defect in partner_financials documentation (capital_items should be been capitals)
Fix defect where partner outgoings are ignored
Fix defect in spreadsheet parser, where housing_cost_type was not read correctly from spreadsheet
=> Lep 77 improve partner and 'single shot' validation

spec/services/calculators/housing_costs_calculator_spec.rb, spec/services/decorators/v5/disposable_income_result_decorator_spec.rb, spec/services/workflows/non_passported_workflow_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-94
Fix up date sensitive tests that were failing post threshold changes on 10th April 2023
=> LEP-94 fix up date-sensitive tests after threshold changes on 10-4-2023
