ministryofjustice/check-financial-eligibility-partner

bin/uat_deploy
As per the thread here: https://mojdt.slack.com/archives/C57UPMZLY/p1669205595197459?thread_ts=1668712333.005529&cid=C57UPMZLY
We need to reduce the length of the name we use for URLs for UAT deployments, this matches what we do on the other repo
- You should …
=> reduce length of branch name used in url

app/services/calculators/subject_matter_of_dispute_disregard_calculator.rb, app/services/capital_collator_and_assessor.rb, app/services/collators/capital_collator.rb, db/migrate/20221128152328_make_assessed_values_nullable.rb, db/schema.rb, features/disputed_assets/disputed_property.feature, features/step_definitions/api_request.rb, features/support/response_support_methods.rb, spec/services/calculators/subject_matter_of_dispute_disregard_calculator_spec.rb, spec/services/collators/capital_collator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-515)
We were trying to sum the values of SMOD assets before we'd assessed the values of those assets, leading to incorrect calculations. This fixes that by moving the summing to later in the process.
=> EL-515: Stop trying to assess smod value prematurely

spec/factories/dependant_factory.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-564)
In tests "aged 15" dependents had a date of birth set to a range that included 16 years before the submission date, meaning their 16th birthday was _on_ the submission date, meaning for the purposes of the calculation they were 16. This was causing approximately 1 test run in every 366 to fail.
This PR fixes the off-by-one error, and also adjusts the other age traits to use all valid date of birth values for those ages.
=> EL-564: Remove test flakiness

app/services/capital_collator_and_assessor.rb, app/services/decorators/v5/capital_result_decorator.rb, app/services/decorators/v5/result_summary_decorator.rb, db/migrate/20230104121138_add_combined_contributions_to_summaries.rb, db/schema.rb, features/partner/partner_assessment.feature, features/step_definitions/api_request.rb, features/support/response_support_methods.rb, spec/services/decorators/v5/capital_result_decorator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-594)
While income contribution is calculated as a single value that already takes into account partner income/outgoing, we currently have separate capital contribution values for applicant and partner, and only the former is being returned in the calculation result. This PR adds a place to store the combined value, and logic to return it to the client.
[EL-594]: https://dsdmoj.atlassian.net/browse/EL-594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EL-594: Return combined capital contribution

.circleci/config.yml
Circle:CI is running the wrong tests on branches due to a copy-and-paste error in the config
=> Fix Copy-N-paste error in circle config

app/services/decorators/v5/disposable_income_result_decorator.rb, app/services/decorators/v5/result_summary_decorator.rb, spec/services/decorators/v5/disposable_income_result_decorator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-621)
Moved it so that we list the partner allowance on the applicant's disposable income summary rather than the partner's disposable income summary (but we only show it above zero if the client actually has a partner)
- You should have …
=> EL-621: Move partner allowance from partner to applicant

app/models/property.rb, features/controlled_work/property_assessment.feature, features/step_definitions/api_request.rb
Based on Patricks el-361 branch so do not review until that has been merged
[Link to story](https://dsdmoj.atlassian.net/browse/AP-632)
Add a check for controlled work before transaction allowance is calculated for property
Add a cucumber test to ensure the transaction_allowance for controlled work assessments is always zero
- You should have looked at the diff against main and ensured that nothing …
=> EL-632 property controlled work calculation

config/initializers/encode_big_decimal_as_number.rb, spec/integration/v5_full_assessment_spec.rb
https://dsdmoj.atlassian.net/browse/EL-622
Fix issue with BigDecimal not being output as a numeric value (rather than a string). This is caused by Rails not wanting to lose precision on a BigDecimal object - which is not an issue for our use-case
=> EL-622 Add tests (and fixes where appropriate) for all capital item

app/models/employment.rb, app/services/calculators/employment_income_calculator.rb, app/services/calculators/employment_income_result.rb, app/services/calculators/multiple_employments_calculator.rb, app/services/collators/disposable_income_collator.rb, app/services/collators/gross_income_collator.rb, app/services/utilities/employment_income_variation_checker.rb, spec/models/employment_spec.rb, spec/services/calculators/employment_income_calculator_spec.rb, spec/services/calculators/multiple_employments_calculator_spec.rb, spec/services/decorators/v5/disposable_income_result_decorator_spec.rb, spec/services/utilities/employment_income_variation_checker_spec.rb
This is a product of the 'functional spike' specifically around the 'Employment Calculator' class(es) which now return an answer (which the upper layer saves to the database) rathe than having the side effect of saving to the database themselves. 
This makes the classes easier to reason about, removes 2 dependencies and also has the side effect of removing duplication - as it turned out both calculators did the database save, whereas now only the (1) higher level has to perform the save.
=> employment calculator returns answer

app/controllers/assessments_controller.rb, app/lib/calculation_output.rb, app/lib/capital_subtotals.rb, app/lib/person_capital_subtotals.rb, app/models/vehicle.rb, app/services/assessors/vehicle_assessor.rb, app/services/capital_collator_and_assessor.rb, app/services/collators/capital_collator.rb, app/services/decorators/v5/assessment_decorator.rb, app/services/decorators/v5/capital_result_decorator.rb, app/services/decorators/v5/result_summary_decorator.rb, app/services/workflows/main_workflow.rb, app/services/workflows/non_passported_workflow.rb, app/services/workflows/passported_workflow.rb, db/migrate/20230131154602_remove_total_vehicles_from_capital_summaries.rb, db/schema.rb, spec/requests/assessments_controller_spec.rb, spec/services/assessors/vehicle_assessor_spec.rb, spec/services/creators/assessment_creator_spec.rb, spec/services/decorators/v5/assessment_decorator_spec.rb, spec/services/decorators/v5/capital_result_decorator_spec.rb, spec/services/workflows/passported_workflow_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-657)
As a first attempt to make CFE's eligibility calculation more functional, I've removed the "total_vehicle" column from the database, instead having its value be returned up the calculation method tree to the assessment controller, and passed into the decorator method tree.
I've not removed the vehicle assessed values from the database, but have moved the vehicle assessment method into VehicleAssessor and made a note of the database-y side effect. One day we'll be able to remove that too, but I think it's out of scope of this ticket.
For now I'm using structs to shape return values lower down the tree, and a CalculationOutput class to define the shape of the overall calculation output. But that's all very up for discussion.
Before …
=> EL-657: Move vehicle total out of the DB

.circleci/config.yml
Change the circle-ci config to correctly call sudo gem update --system so that it doesn't fail with permission denied
=> Update system gems with sudo - otherwise it fails with permission denied

app/lib/calculation_output.rb, app/lib/capital_subtotals.rb, app/lib/person_capital_subtotals.rb, app/services/assessors/capital_assessor.rb, app/services/capital_collator_and_assessor.rb, app/services/collators/capital_collator.rb, app/services/decorators/v5/capital_result_decorator.rb, app/services/decorators/v5/result_summary_decorator.rb, app/services/remark_generators/orchestrator.rb, app/services/remark_generators/residual_balance_checker.rb, app/services/workflows/main_workflow.rb, db/migrate/20230206104737_remove_columns_from_capital_summaries.rb, db/migrate/20230206122959_remove_more_columns_from_capital_summaries.rb, db/schema.rb, spec/services/collators/capital_collator_spec.rb, spec/services/creators/assessment_creator_spec.rb, spec/services/decorators/v5/capital_result_decorator_spec.rb, spec/services/remark_generators/orchestrator_spec.rb, spec/services/remark_generators/residual_balance_checker_spec.rb, spec/services/workflows/main_workflow_spec.rb, spec/services/workflows/passported_workflow_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-658)
Move attributes to return object.
In addition to the properties listed on the ticket, it also made sense to remove:
- combined_assessed_capital
- pensioner_capital_disregard
- subject_matter_of_dispute_disregard
Also, as these fields are not actually used anywhere any more, I _did_ remove
- upper_threshold
- lower_threshold
(The actual thresholds are stored elsewhere)
- The PR description should say what you changed and why, with a …
=> EL-658: Remove attributes from capital summary

Dockerfile
Using multistage Dockerfile to reduce the Docker image size, by excluding from the final image: bundler and associated build packages.
Smaller image is good:
* quicker image download, and thus pod start-ups
* less attack surface
The "--virtual build-dependencies" trick wasn't working, since every CMD creates a layer in the image, so the trick only works if you delete the build dependencies again in the same CMD. Multistage dockerfile is the preferred method.
No Jira story.
Testing done on the command-line - not to the end, but seems ok:
```
% export CFE=https://docker-image-smaller-check-financial-partner-uat.cloud-platform.service.justice.gov.uk/
% curl -X POST $CFE/assessments -d '{"client_reference_id": "LA-FOO-BAR",  "submission_date": "2022-05-19", "level_of_representation": …
```
=>  Docker image size reduced 785MB -> 169MB

app/constants/cfe_constants.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-719)
Clear out old assessments after 14 days instead of 30.
=> EL-719: Reduce threshold for clearing out old assessments

features/disputed_assets/disputed_capital_items.feature, features/disputed_assets/disputed_property.feature, features/disputed_assets/disputed_vehicle.feature, features/partner/partner_assessment.feature, features/step_definitions/api_request.rb
Cucumber tests refer to 'standard' checks when they mean 'certificated' - this converts these to use the better terminology
=> rename 'standard' to 'certificated' in cucumber tests

app/services/legal_framework_api/mock_threshold_waivers.rb, app/services/utilities/proceeding_type_threshold_populator.rb, spec/services/legal_framework_api/mock_threshold_waivers_spec.rb, spec/services/utilities/proceeding_type_threshold_populator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/EL-638)
We've started sending through certificated assessments with upper tribunal proceeding types, which LFAPI can't handle. So this stops sending these types to LFAPI.
=> EL-638: Ignore LFAPI for upper tribunal matter types

app/lib/person_capital_subtotals.rb, app/services/collators/capital_collator.rb, app/services/decorators/v5/capital_result_decorator.rb, features/pensioner/pensioner_disregard.feature, features/step_definitions/api_request.rb, spec/requests/swagger_docs/v5/full_assessment_spec.rb, spec/requests/v2/assessments_controller_spec.rb, spec/services/collators/capital_collator_spec.rb, spec/services/decorators/v5/capital_result_decorator_spec.rb, swagger/v5/swagger.yaml
https://dsdmoj.atlassian.net/browse/EL-765
CCQ needs to know how much pensioner capital disregard was applied to the capital calculation so that it can present a sensible set of sums to the user that make sense
=> EL-765 expose pensioner disregard in capital section

app/services/decorators/v5/capital_result_decorator.rb, app/services/decorators/v5/disposable_income_result_decorator.rb, app/services/decorators/v5/gross_income_result_decorator.rb, app/services/decorators/v5/proceeding_types_result_decorator.rb, app/services/decorators/v5/result_summary_decorator.rb, spec/services/decorators/v5/proceeding_types_result_decorator_spec.rb, spec/spec_helper.rb
Proceeding types decorator had 2 types of instantiation, and a dynamic switch to choose between them - hence there was a 'phantom' 3rd state which could never be reached. Replace dynamic switch with knowledge at calling site
=> EL-710: Proceeding types decorator simplification

app/controllers/status_controller.rb, config/routes.rb, deploy/helm/templates/deployment_web.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/EL-746)
- Uncrossed the status paths (/status/ was pointing at the ping method, as was /ping/, while there's a status method that only /healthcheck/ was pointing at) for readability / predictability
- Changed the k8s liveness probe to use the /status/ endpoint, which checks the database
- Added a check to the /status/ endpoint to check that the schema has been loaded
=> El 746: Liveness probe checks that the schema is loaded

.circleci/config.yml, Gemfile, Gemfile.lock, spec/spec_helper.rb
https://dsdmoj.atlassian.net/browse/El-710
While branch coverage is incomplete, coverage regressions can take place due to refactorings. This adds the 'undercover' tool to the pipeline to add an extra check, which can be removed if and when we achieve 100% branch coverage
=> EL-710 add undercover to prevent coverage regressions 

Gemfile.lock
Upgrade to bundler 2.4.7 (which is the default with ruby 3.2)
=> Bundler 2.4

README.md
When running bin/setup to install the gems I hit this error:
```
Installing rugged 1.5.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory: /Users/david.read/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rugged-1.5.1/ext/rugged
/Users/david.read/.rbenv/versions/3.2.1/bin/ruby -I /Users/david.read/.rbenv/versions/3.2.1/lib/ruby/3.2.0 extconf.rb
checking for gmake... no
checking for make... yes
checking for cmake... no
ERROR: CMake is required to build Rugged.
```
I fixed it by installing cmake, so I've added it to the README.
'rugged' was a introduced yesterday, as a dependency of 'undercover' in #118
Also brew's postgres needs to be started manually on every boot by default, so for convenience I added the command to get it to …
=> Fix "rugged" gem install

features/step_definitions/api_request.rb
During a previous refactoring, a defect was added to the test structure, possibly leading to a future 'false positive' test pass.
=> Fix-up test refactoring

app/services/assessors/property_assessor.rb, app/services/calculators/property_calculator.rb, app/services/utilities/number_utilities.rb, features/disputed_assets/disputed_property.feature, features/disputed_assets/multiple_disputed_assets.feature, features/partner/partner_assessment.feature, features/property/property.feature, spec/integration/v5_full_assessment_spec.rb, spec/requests/v2/assessments_controller_spec.rb, spec/services/calculators/property_calculator_spec.rb, spec/swagger_helper.rb, swagger/v5/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-42
This makes 2 subtle changes to the semantics of the 'property' fields, which are not thought to be breaking changes:
a) main_property_equity_disregard was always set to 100_000 - this is now the actual main disregard in use
b) transaction_allowance was always 3% of property value - it is now less than that (but non-zero) if the equity is less than the transaction allowance
=> Lep 42 expose allowances for properties

.circleci/config.yml
This is an update of cloud-platform-tool image to the latest, 2.3.0. I believe this updates to aws cli v2, hence the ECR login update.
This PR is a copy of the fix here: https://github.com/ministryofjustice/check-financial-eligibility/pull/1348/files
**Cause**
Colin said:
> Github updated their SSH key at 05:00UTC this morning… https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key
> This has broken some of our circle deploys as the executor we use seems to have cached the old version
(No Jira ticket)
- There should be no unnecessary whitespace changes. These make diffs harder to read and …
=> Update cloud-platform-tools image to fix circle deploy

app/lib/employment_income_subtotals.rb, app/services/collators/disposable_income_collator.rb, app/services/collators/gross_income_collator.rb, app/services/decorators/v5/disposable_income_result_decorator.rb, app/services/workflows/non_passported_workflow.rb, db/migrate/20230324150833_remove_employment_from_disposable_income.rb, db/schema.rb, spec/services/collators/disposable_income_collator_spec.rb, spec/services/collators/gross_income_collator_spec.rb, spec/services/decorators/v5/disposable_income_result_decorator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-22
As part of LEP-22/EL-688, remove employment summary figures from disposable income summary. These figures were already returned and passed to the decorator display layer
=> LEP-22 Stop persisting employment values in disposable_income_summary

app/lib/calculation_output.rb, app/lib/disposable_income_subtotals.rb, app/services/collators/disposable_income_collator.rb, app/services/collators/outgoings_collator.rb, app/services/decorators/v5/assessment_decorator.rb, app/services/decorators/v5/deductions_decorator.rb, app/services/decorators/v5/disposable_income_decorator.rb, app/services/decorators/v5/disposable_income_result_decorator.rb, app/services/decorators/v5/result_summary_decorator.rb, app/services/workflows/non_passported_workflow.rb, db/migrate/20230327082347_remove_dependant_allowance.rb, db/schema.rb, spec/factories/disposable_income_summary_factory.rb, spec/services/collators/disposable_income_collator_spec.rb, spec/services/decorators/v5/deductions_decorator_spec.rb, spec/services/decorators/v5/disposable_income_result_decorator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-22
Following on from removing employment fields, this removes the dependant allowance and passes it along the chain in the output
=> LEP-22 Remove dependant allowance from disposable_income_summary

app/controllers/outgoings_controller.rb, app/services/creators/full_assessment_creator.rb, app/services/creators/outgoings_creator.rb, app/services/creators/partner_financials_creator.rb, spec/fixtures/partner_financials.json, spec/requests/partner_financials_controller_spec.rb, spec/requests/swagger_docs/v5/cash_transactions_spec.rb, spec/requests/swagger_docs/v5/full_assessment_spec.rb, spec/requests/swagger_docs/v5/outgoings_spec.rb, spec/requests/swagger_docs/v5/partner_financials_spec.rb, spec/requests/v2/assessments_controller_spec.rb, spec/services/creators/outgoings_creator_spec.rb, spec/services/creators/partner_financials_creator_spec.rb, spec/swagger_helper.rb, swagger/v5/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-81
Add 'outgoings' section to partner_financials endpoint to match 'outgoings' endpoint in existing API. 
Fix-up documentation for 'capitals' section of partner_financials (capitals rather than capital_items)
=> LEP-81 Add outgoings to partner financials endpoint

app/services/calculators/property_calculator.rb, db/migrate/20230329105231_remove_property_results.rb, db/schema.rb, spec/services/calculators/subject_matter_of_dispute_disregard_calculator_spec.rb, spec/services/decorators/v5/property_decorator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-6
As part of removing the persistence from CFE, remove the calculated property fields from the database as they are already returned and used by the decorator
=> LEP-6: Remove property calculations from database table

spec/requests/swagger_docs/v5/partner_financials_spec.rb, spec/swagger_helper.rb, swagger/v5/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-77
As part of LEP-77, the partner financials endpoint 'employments' documentation was found to have an error. This corrects that error
=> LEP-77: Fix partner financials documentation bug

db/migrate/20230331170201_remove_and_update_timestamp_columns.rb, db/schema.rb, spec/models/assessment_spec.rb, spec/services/creators/capitals_creator_spec.rb
[LEP-71](https://dsdmoj.atlassian.net/browse/LEP-71)
**We need to remove/update timestamp so that the time can’t be correlated with CCQ logs**
- Change timestamp column for `assessments` from `datetime` to `date`
- Remove timestamp column from all tables, apart from `assessments` and `bank_holidays`
[LEP-71]: https://dsdmoj.atlassian.net/browse/LEP-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LEP-71 assessment timestamp should be recorded less accurately

spec/services/collators/childcare_collator_spec.rb
One stray spec started failing on 4-4-2023 due to it relying on things not changing and Date.current
=> Change test not to rely on Date.current

spec/swagger_helper.rb, swagger/v5/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-57
Fix a bug where legacy field in partner employment was marked as numeric rather than currency
=> LEP-57 defect - net_employment_income should be currency

Gemfile, Gemfile.lock, config/initializers/rainbow.rb
[LEP-82](https://dsdmoj.atlassian.net/browse/LEP-82)
- Replace `colorize` gem wirh `rainbow` because snyk highlighted [this issue](https://app.snyk.io/org/legal-aid-agency/project/a84bdfb6-d142-4618-86a9-395a5b9903da#issue-snyk:lic:rubygems:colorize:GPL-2.0)
- `rainbow` is already a dependency of `undercover` and `rubocop` gems so we just need to remove `colorize` gem
[LEP-82]: https://dsdmoj.atlassian.net/browse/LEP-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LEP-82 - Replace colorize gem with rainbow
